### ISSUE TITLE
Remove dependency on nrfcloud-web-frontend

### ISSUE THREAD

**Issue by coderbyheart** [nRFCloud/aws-client#2]
This package [dependes on nrfcloud-web-frontend](https://github.com/nRFCloud/aws-client/blob/920338859b78b40fa8af70c1635caa4826a948f2/package.json#L32) which includes this as a library. 

This means that other projects need to pull it in, just for logging (like the [PC Gateway](https://github.com/NordicPlayground/cloud-iris-gateway/pull/27)).

Logically this is also a circular dependency.

**Comment by TheBosZ** [comment]
Yeah, we're only using the Logger and it's only used to output an error when a sync fails. There's no reason to pull in a whole project just for that.
