### ISSUE TITLE
REST API client v2 removes AWS SDK in bundle

### ISSUE THREAD

**Issue by coderbyheart** [nRFCloud/aws-client#21]
For https://github.com/NordicPlayground/nrfcloud-web-frontend/pull/472 there is a new version of the IRIS REST SDK without bundled aws-sdk: https://github.com/nRFCloud/iris-api-gateway/pull/4

The question is whether this change is good for `aws-client` and it can use it's own bundler to include the necessary dependencies, or if the change to `iris-api-gateway` should be reverted.

**Comment by TheBosZ** [comment]
I haven't tried to actually use this yet, but with just reading the code, it **should** be fine.

The gateway uses the gateway-common repo that [has its own dependency](https://github.com/nRFCloud/gateway-common/blob/master/src/GatewayAWS.ts#L46) on `aws-iot-device-sdk` (see also the [package.json](https://github.com/nRFCloud/gateway-common/blob/master/package.json#L25)).

The gateway code itself really only uses the API client for three things: getting the tenant, getting the list of gateways and creating a gateway.

The gateway uses a slightly modified REST SDK to allow switching between backends, but it shouldn't be hard to modify the bundle to account for this.

**Comment by TheBosZ** [comment]
I **am** using the MQTT client, so there's a bit of munging around. Not a big deal so far.

**Comment by TheBosZ** [comment]
Oops. Didn't see that all the old `.http.` methods are now just on the client.

**Comment by TheBosZ** [comment]
Okay, I can officially get as far as possible (`https://hnmr2uba55.execute-api.us-east-1.amazonaws.com/dev/tenants/8d7a246e-eb2c-4c20-954d-3e9a2db71168/gateways` returns a 500 right now).

So I'm going to call this a success. If another problem pops up, I'd rather handle it on the gateway side.

Makes the client that much smaller so I think it's a good change.
